[build-system]
requires = [
    "setuptools>=77,<81",
    "wheel",
]
build-backend = "setuptools.build_meta"

[project]
name = "OctoPrint-PluginTemplate"
version = "0.0.0"
description = "Starter template for building OctoPrint plugins"
authors = [
    {name = "Ajimaru", email = "ajimaru_gdr@pm.me"}
]
readme = {file = "README.md", content-type = "text/markdown"}

requires-python = ">=3.11, <4"

classifiers = [
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]

# Add runtime dependencies for your plugin here (besides OctoPrint itself)
dependencies = [
]

[tool.setuptools]
include-package-data = true

[tool.setuptools.package-data]
octoprint_plugin_template = [
    "translations/**/*.po",
    "translations/**/*.mo",
    "translations/**/*.pot",
]

[tool.setuptools.packages.find]
include = [
    "octoprint_plugin_template",
    "octoprint_plugin_template.*"
]

[project.entry-points."octoprint.plugin"]
plugin_template = "octoprint_plugin_template"

[project.urls]
Homepage = "https://github.com/Ajimaru/octoprint_plugin_template"
Repository = "https://github.com/Ajimaru/octoprint_plugin_template"
Issues = "https://github.com/Ajimaru/octoprint_plugin_template/issues"

[project.optional-dependencies]
develop = [
    "pytest>=7,<10",
    "pytest-cov",
    "pre-commit>=3,<5",
    "black>=24.0.0",
    "isort>=5,<8",
    "flake8>=7.0.0"
]
