[build-system]
requires = [
    "setuptools>=77,<81",
    "wheel",
    "OctoPrint",
]
build-backend = "setuptools.build_meta"

[project]
name = "OctoPrint-Uptime"
version = "0.1.0-dev3"
description = "OctoPrint plugin that exposes system uptime to the About â†’ System dialog"
authors = [
    {name = "Ajimaru", email = "ajimaru_gdr@pm.me"}
]
readme = {file = "README.md", content-type = "text/markdown"}

requires-python = ">=3.10, <4"

classifiers = [
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]

# Add runtime dependencies for your plugin here (besides OctoPrint itself)
dependencies = [
]

[tool.setuptools]
include-package-data = true

[tool.setuptools.package-data]
octoprint_uptime = [
    "translations/**/*.po",
    "translations/**/*.mo",
    "translations/**/*.pot",
]

[tool.setuptools.packages.find]
include = [
    "octoprint_uptime",
    "octoprint_uptime.*"
]

[project.entry-points."octoprint.plugin"]
octoprint_uptime = "octoprint_uptime"

[project.urls]
Homepage = "https://github.com/Ajimaru/OctoPrint-Uptime"
Repository = "https://github.com/Ajimaru/OctoPrint-Uptime"
Issues = "https://github.com/Ajimaru/OctoPrint-Uptime/issues"

[project.optional-dependencies]
develop = [
    "pytest>=7,<10",
    "pytest-cov",
    "pre-commit>=3,<5",
    "black>=24.0.0",
    "isort>=5,<8",
    "flake8>=7.0.0"
]
